/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "y",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        HkGrotesk: ["HK Grotesk", "sans-serif"],
        biotifBold: ["biotif-bold", "sans-serif"],
        biotifBlack: ["biotif-black", "sans-serif"],
        biotifMedium: ["biotif-medium", "sans-serif"],
        biotifRegular: ["biotif-regular", "sans-serif"],
        moderat: ["Moderat", "sans-serif"],
        millik: ["Millik Regular", "sans-serif"],
        milligramLight300: ["Milligram Trial Light", "sans-serif"],
        milligramRegular400: ["Milligram Trial Regular", "sans-serif"],
        milligramBold700: ["Milligram Trial Bold", "sans-serif"],
        avenirRoman: ["avenir-roman", "sans-serif"],
        avenirBlack: ["avenir-black", "sans-serif"],
        avenirBook: ["avenir-book", "sans-serif"],
        avenirMedium: ["avenir-medium", "sans-serif"],
        avenirHeavy: ["avenir-heavy", "sans-serif"],
        avenirRegular: ["avenir-regular", "sans-serif"],
        avenirLight: ["avenir-light", "sans-serif"],
        grinched: ["Grinched", "sans-serif"],
        spaceGroteskBold: ["spacegrotesk-bold", "sans-serif"],
        spaceGroteskLight: ["spacegrotesk-light", "sans-serif"],
        spaceGroteskMedium: ["spacegrotesk-medium", "sans-serif"],
        spaceGroteskRegular: ["spacegrotesk-regular", "sans-serif"],
        DegularDiplayThinItalic: ["degulardisplay-thinitalic", "sans-serif"],
        DegularDiplayThin: ["degulardisplay-thin", "sans-serif"],
        DegularDiplaySemiBoldItalic: ["degulardisplay-semibolditalic", "sans-serif"],
        DegularDiplaySemiBold: ["degulardisplay-semibold", "sans-serif"],
        DegularDiplayRegularItalic: ["degulardisplay-regularitalic", "sans-serif"],
        DegularDiplayRegular: ["degulardisplay-regular", "sans-serif"],
        DegularDiplayMediumItalic: ["degulardisplay-mediumitalic", "sans-serif"],
        DegularDiplayMedium: ["degulardisplay-medium", "sans-serif"],
        DegularDiplayLightItalic: ["degulardisplay-lightitalic", "sans-serif"],
        DegularDiplayLight: ["degulardisplay-light", "sans-serif"],
        DegularDiplayBoldItalic: ["degulardisplay-bolditalic", "sans-serif"],
        DegularDiplayBold: ["degulardisplay-bold", "sans-serif"],
        DegularDiplayBlackItalic: ["degulardisplay-blackitalic", "sans-serif"],
        DegularDiplayBlack: ["degulardisplay-black", "sans-serif"],
        TrapSemiBold: ["trap-semibold", "sans-serif"],
        TrapRegular: ["trap-regular", "sans-serif"],
        TrapMedium: ["trap-medium", "sans-serif"],
        TrapLight: ["trap-light", "sans-serif"],
        TrapExtraBold: ["trap-extrabold", "sans-serif"],
        TrapBold: ["trap-bold", "sans-serif"],
        TrapBlack: ["trap-black", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        brandConcrete:"#f3f3f3",
        brandCodGray: "#080808",
        brandStack: "#929593",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
